### ISSUE TITLE
Issues with Blasphemous

### ISSUE THREAD

**Issue by ZVak18** [z0z0z/mf-install#21]
Saw this as a recommended workaround for Blasphemous.
Using the script as mentioned, I'm still having issues getting the game to load it's video proper.
I am seeing some errors when running this script, any chance for a pointer in the right direction?

```
WINEPREFIX="/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx" ./install-mf.sh
'syswow64/colorcnv.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/colorcnv.dll'
'syswow64/mf.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/mf.dll'
'syswow64/mferror.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/mferror.dll'
'syswow64/mfplat.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/mfplat.dll'
'syswow64/mfplay.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/mfplay.dll'
'syswow64/mfreadwrite.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/mfreadwrite.dll'
'syswow64/msmpeg2adec.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/msmpeg2adec.dll'
'syswow64/msmpeg2vdec.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/msmpeg2vdec.dll'
'syswow64/sqmapi.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/syswow64/sqmapi.dll'
'system32/colorcnv.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/colorcnv.dll'
'system32/mf.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/mf.dll'
'system32/mferror.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/mferror.dll'
'system32/mfplat.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/mfplat.dll'
'system32/mfplay.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/mfplay.dll'
'system32/mfreadwrite.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/mfreadwrite.dll'
'system32/msmpeg2adec.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/msmpeg2adec.dll'
'system32/msmpeg2vdec.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/msmpeg2vdec.dll'
'system32/sqmapi.dll' -> '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx/drive_c/windows/system32/sqmapi.dll'
002c:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
002c:fixme:dwmapi:DwmIsCompositionEnabled 000000006DBD1518
002e:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0x310ac0, init_notify 0, handle 0x135f9d0):
stub
002c:fixme:ntdll:EtwEventRegister ({f404b94e-27e0-4384-bfe8-1d8d390b0aa3}, 0x7ff385dce74, 0x7ff3861f800, 0x7ff3861f118) stub.
002c:fixme:ntdll:EtwEventRegister ({bc97b970-d001-482f-8745-b8d7d5759f99}, 0x7ff385dce74, 0x7ff3861f7d0, 0x7ff3861f110) stub.
002c:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
002c:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0054:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0054:fixme:dwmapi:DwmIsCompositionEnabled 6D5D3018
0056:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0cb608, context 0x3aeaa8, init_notify 0, handle 0x121fce8):
stub
0054:err:module:load_so_dll failed to load .so lib "/usr/bin/../lib32/wine/winegstreamer.dll.so": libgstvideo-1.0.so.0: cannot open shared object file: No such file or directory
wine: configuration in '/home/zyneris/.local/share/Steam/steamapps/compatdata/774361/pfx' has been updated.
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
regsvr32: Successfully registered DLL 'msmpeg2vdec.dll'
regsvr32: Successfully registered DLL 'msmpeg2adec.dll'
regsvr32: Successfully registered DLL 'colorcnv.dll'
regsvr32: Successfully registered DLL 'msmpeg2vdec.dll'
regsvr32: Successfully registered DLL 'msmpeg2adec.dll'
regsvr32: Successfully registered DLL 'colorcnv.dll'
```

**Comment by telans** [comment]
Chances are that this workaround just doesn't fix the game. 

`err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated` 
refers to the `libwbclient` package being missing.

`err:module:load_so_dll failed to load .so lib "/usr/bin/../lib32/wine/winegstreamer.dll.so": libgstvideo-1.0.so.0:` 
refers to the `gst-plugins-base` package being missing

**Comment by ionenwks** [comment]
I was just trying Blasphemous myself for the first time (GOG version with wine-staging 4.19 + dxvk 1.4.4 on gentoo -- winelib dxvk was failing for some reason, winetricks one is fine), didn't play much yet but game seems fine thanks to mf-install.

ntlm_auth can be ignored, you should never need this for games. The only reason people install it is typically to suppress the harmless error message, but you can mask this by using WINEDEBUG if it really bothers you.

Your problem is probably gstreamer, make sure it's installed + plugins (and your wine build supports it), video playback seems to fail if I disable winegstreamer in winecfg, so.. I'm not sure but it "seem" to use h264 which should be offered by the ffmpeg/libav plugin "gst-plugins-libav" or so (whatever your distribution names it), so makes sure that's installed (having all of -good/-base/-ugly/-libav plugins doesn't hurt, I do skip on -bad though -- Edit: preferably both 32bit and 64bit too, blasphemous only needs 64bit though).

Worst case if you don't want to figure it out, Blasphemous devs do have a native linux version planned, no idea when that's releasing though.

**Comment by ZVak18** [comment]
Thanks for the replies. I'm actually doing this through the Steam version of Blasphemous, so not sure if maybe that's part of the issue with the missing libs?

If I wanted to install the "gst....", should i be able to find that via my distro or would it be better to use protontricks to get everything I need? I currently don't use nor have protontricks, but I've seen people say it helps on Protondb. Thanks!

**Comment by z0z0z** [comment]
@ZVak18 The various gstreamer packages are Linux software that you would typically find in your distro's repositories. They aren't modifications you would do to a Wine prefix.

**Comment by ionenwks** [comment]
To correct what I was saying before, I don't think it actually "use" gstreamer (mf dlls are doing the decoding). I think wine is just randomly failing if it's not in a working state. So just having base plugins is enough.

**Comment by ZVak18** [comment]
Thanks so much for the help! I was able to get rid of the errors by installing the gst packages, but still not able to get the cut scenes to load.
I will assume it's simply not able to work at this point.

**Comment by MrJakob99** [comment]
I know it's not the right threat here, but pls help! 
How  do I set a WINEPREFIX !? 
I executed the .sh file an it said 'no WINEPREFIX set' ... I have no idea how to do that

**Comment by z0z0z** [comment]
@MrJakob99 
> I know it's not the right threat here, but pls help!
> How do I set a WINEPREFIX !?
> I executed the .sh file an it said 'no WINEPREFIX set' ... I have no idea how to do that

As described in the README.

`WINEPREFIX="/path/to/your/wine/prefix" ./mf-install.sh`

You must know where your Wine prefix is of course. By default, Wine creats one in `$HOME/.wine`

**Comment by MrJakob99** [comment]
Okay, so I found my prefixes. I'm using proton through steam, so they are in the steam folder. 
I assume I can just pick one of them (there are around 10) with the newest proton version (will it automatically be picked when I start the game?)
Then type 'WINEPREFIX=home/.steam/..../35182041(<-random number) mf-install.sh' in the terminal.
But where do I place the content of the mf-master-installer.zip ? Inside the prefix folder which I selected? Shouldn't the install.sh be in the folder where it is installed?

**Comment by z0z0z** [comment]
@MrJakob99 
You are all kinds of confused.

1) You download and extract mf-install, or `git clone` it.

2) You open a terminal in the same directory as `mf-install.sh`. If you type `ls` you should see it listed, and if you type `pwd` you will see the directory you're at in the terminal.

3) WINEPREFIX is an environment variable, you set it to point at the Wine prefix you want.

4) You execute the script with WINEPREFIX set, all in one line: 
`WINEPREFIX="/home/.steam/..../35182041/pfx" ./mf-install.sh`

That's it, done.

**Comment by ZVak18** [comment]
Closed as my issue was resolved via [this find](https://github.com/z0z0z/mf-install/issues/44).
