### ISSUE TITLE
~/.steam/steam/steamapps/compatdata/774361/pfx isn't a valid path

### ISSUE THREAD

**Issue by stitch1231** [z0z0z/mf-install#42]
Hello!

I'm trying to install the fix to play Blasphemous.

I used these three commands:

`export WINEPREFIX="~/.steam/steam/steamapps/compatdata/774361/pfx"`
`export PROTON="~/.steam/steam/steamapps/common/Proton 4.11"`
`./mf-install.sh -proton`

The last one prints the error in the title. I am pretty sure that it IS a valid path.

Have anyone encountered this issue? Am I missing something?

**Comment by z0z0z** [comment]
Try `$HOME` instead of `~`.

**Comment by stitch1231** [comment]
Thank you, but now I'm getting this after running the install command.

`./mf-install.sh: 23: export: 4.11/dist/bin:/home/stepan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: bad variable name`

Is it because my Steam is installed in ~/.steam instead of ~/.local/shared?

I'm kinda lame with Linux, so apologies if I'm asking stupid questions.

**Comment by z0z0z** [comment]
`4.11/dist/bin:/home/stepan/.local/bin`

You  can see it's added a relative (not absolute) path called "4.11/dist/bin" to your $PATH.

This is likely the full path "$HOME/.local/share/steam/steamapps/common/Proton 4.11"

Except it got butchered at the first space in "Proton 4.11". Why? I don't know. What exactly did you do, and did you edit the script?

**Comment by stitch1231** [comment]
I didn't edit the script. The thing is... there is no "steam" folder in my $HOME/.local/share/. My Steam is installed in $HOME/.steam/.

I think that's the issue? The script assumes it's in .local?

**Comment by z0z0z** [comment]
The script doesn't assume it's path at all.

The paths are exclusively specified by you, through setting the `WINEPREFIX` environment variable, and **optionally** an environment variable called `PROTON`.

You could have it set to `WINEPREFIX="/root/anime/wine prefixes/foobar"`.

And that would be valid so long as you have a Wine prefix there.

Steam by default installs itself into `$HOME/.local/share/Steam`, with folders symlinking to it in `$HOME/.steam`.

Note that "Steam" is different from "steam", filenames are case sensitive in Unix.

**Comment by stitch1231** [comment]
Alright, I will try to use the .local paths then. Thank you.

**Comment by z0z0z** [comment]
The `$HOME/.steam` paths should work fine too, you don't actually need to use $HOME/.local/share directly. There's something you're doing that isn't right.

The script doesn't care about using $HOME, or symlinks to the folder, or spaces, I just tried this myself:

`WINEPREFIX="$HOME/.steam/steam/steamapps/compatdata/582010/pfx" PROTON="$HOME/.steam/steam/steamapps/common/Proton 4.11" ./mf-install.sh -proton`

It does care if you use "~", but only because Wine itself doesn't like that.

**Comment by stitch1231** [comment]
Here's a screenshot that should show everything important, that is where I extracted the installer, and what I put into my terminal: https://i.imgur.com/o3oW8V2.png

**Comment by z0z0z** [comment]
Well that is right, even if you did extract mf-install to the folder for some reason.

At this point I'm curious why that doesn't work for you. Are you on some alternative shell other than bash? Like fish?

`echo $SHELL`

**Comment by stitch1231** [comment]
Nope, this is a default Ubuntu 18.04 installation. That command prints /bin/bash. I'll try to put the extracted files into a separate folder then.

**Comment by z0z0z** [comment]
That shouldn't make a difference either.

I'm baffled as to why that doesn't work for you. I don't know what else to say, there is black magic on your system.

**Comment by z0z0z** [comment]
I think I may know what the problem is.

Ubuntu may be using dash instead of bash as your default shell for `#!/bin/sh`.

Try doing the same thing but specifically specify `bash mf-install.sh -proton`

**Comment by stitch1231** [comment]
This worked! Thanks a lot for your time and help!

**Comment by z0z0z** [comment]
Thanks for reporting the issue, because of this I'm gonna change the shebang to `#!/bin/bash`.

Even though everything in the script should be shell independent, I guess some shells still have problems with basic stuff.

**Comment by michaelforney** [comment]
I don't think there is anything wrong with "basic stuff" with dash, it is following the POSIX standard.

In
```
export WINEDLLPATH=""$PROTON"/dist/lib/wine:"$PROTON"/dist/lib64/wine"
```
why do you leave $PROTON outside of the quotes? That means that it is subject to field splitting, which is causing the issue.

I think
```
export WINEDLLPATH="$PROTON/dist/lib/wine:$PROTON/dist/lib64/wine"
```
is what you want here, and should work fine.

**Comment by z0z0z** [comment]
With that I was specifically trying to encapsulate the variable within quotes, so no matter what crazy path full of characters like # ! @ $ % someone might have it in, it gets quoted.

You're right though, after testing this, it isn't proper.
