### ISSUE TITLE
More newbie proof installation info

### ISSUE THREAD

**Issue by michaldybczak** [z0z0z/mf-install#46]
I have a Steam game, so I'm using Steam proton. What do I do? The instruction is completely unclear.

"Just set WINEPREFIX and run."

What is "set" means in that context? And is it applicable with Proton? And If I already have Proton with steam and don't need to set it, do I have to do something additional before launching the script?

What does it do? I understand I should apply it to my user, my folders and my game, so the path will change, but what export command do and can I run it just as it is without doing something before, like this "setting" things?
`export WINEPREFIX="/home/gaben/.local/share/Steam/steamapps/compatdata/751440/pfx"`

When I used:

`export WINEPREFIX="/home/michaldybczak/mnt/home-hdd/SteamLibrary/steamapps/compatdata/585450/pfx/"`

it did nothing, or at least I can't tell if it did something. The prompt was ready to receive the new command. So did it work? Should it do something or is it normal?

This seems to be clearer. But is this a one command or two?
```

export PROTON="/home/gaben/.local/share/Steam/steamapps/common/Proton 4.11"
./mf-install.sh -proton
```

In my case, it may be:
`
export PROTON="/mnt/home-hdd/SteamLibrary/steamapps/common/Proton 4.11/"`

Like the previous command, it just jumped to the next line. Did it do something?

When I use `./mf-install.sh -proton`

I get:

WINEPREFIX is not set

So again, what SET means and how do we SET it?

When I repeated the previous two commands and the last one again in the same location and terminal window, I got different result:

`/home/michaldybczak/mnt/home-hdd/SteamLibrary/steamapps/compatdata/585450/pfx/ isn't a valid path`

Please, we need newbie or idiot ;) proof instructions. Nothing should be left to the imagination, nothing could be unclear or confusing. As you can see, too many things can be messed using your incomplete instruction/

So:
1. Open terminal.
2. Do this command but change your path and the game folder (you can find it with protontricks)
3. Do this command, etc.

Currently, I have too many possibilities and I'm just confused. I know the path and the game's number (thanks to protontricks) but what next?

Ah, I messed the path. My mounted location doesn't go through my home folder... so I corrected the paths, used both export command and the last install one and something is doing. Yay! I got success output. Hopefully this will make the game playable.

**Comment by z0z0z** [comment]
The script has many safeguards as you found out, if you give it incorrect paths, it will refuse to run until you do.

`So again, what SET means and how do we SET it?`
It's an environment variable, they're very simple. I'm not going to verbosely explain how environment variables work in the README.

Should I also explain to you how folders work? Because you and some people obviously also need that.

Should I explain how to copy and paste file paths from your file manager?

`Like the previous command, it just jumped to the next line. Did it do something?`

Do `echo $FOOBAR` to see the value of a variable.

`Do this command but change your path and the game folder (you can find it with protontricks)`
I feel like I'm honestly insulting the vast majority of user's intelligence by even mentioning this. Also you don't need protontricks at all to find your steam folder.

**Comment by michaldybczak** [comment]
Previously I installed mf to the game's proton's prefix but that didn't work. However, the game became fully playable after using your script.

As to the request, yes, some things may be obvious to majority if linux users but not all will know such basics. On a daily basis I don't need to set any environmental variables and till day this is somewhat fuzzy concept to me, so any instructions involving it create a great deal of questions.

Since game proton folders contain from numbers, so we cannot know the proper proton sub-folder, one must have a way to determine this. I use it protontricks for it. If there are other ways, I don't know them. I can only imagine that some may not know any method, hence the need for a hint where to get it (a full blow instruction is not needed).

Once I succeeded with your script, now the instructions look clear. However, before that, it was very unclear and left much to imagine. There are thousands of linux users who do need step by step instruction. If everyone in Linux word would put good instruction or documentations, Linux probably would be more widely used on desktops.

Developers may be brilliant, skilled and knowledgeable but lack of imagination to understand the hardship for not technical or newbie users. Because of that we had tons of tons technical and unusable gibberish that prevents us (users) from using the code you wrote.

Please, remember that your effort is wasted if you aim your documentation only for skilled individuals like yourself, because the majority of average users will not get it. It's also frustrating that we must look for fixes and decipher cryptic documentation. This creates a steep learning curve and requires greater effort to do things that should be simple and quick. Many users simply bounce off and won't come back to Linux because it was too hostile and it was hostile, because it was created by devs for devs and alike, but not for average users.

I'm closing this case, since I got what I came for and your script was very helpful. Thanks for that.
Since you have a different mindset and you are not willing to improve average user-friendly documentation, my effort is probably wasted anyway.

**Comment by z0z0z** [comment]
`Since game proton folders contain from numbers, so we cannot know the proper proton sub-folder, one must have a way to determine this. I use it protontricks for it. If there are other ways, I don't know them.`

You can look in the folder with your file manager lol

I did decide to update the README today btw.

**Comment by michaldybczak** [comment]
Yeah, I can browse it but it's hard to find what game is installed there, so this is a tedious task. Protontricks is the quickest and easiest way. I just run:

`protontricks --gui`

and then a GUI is launched where I can choose the game and see the number. It's just few seconds. Way quicker than trying to browse the depths of steam folders. Probably I could create a .destop file to launch it, so it would be two clicks away.

The game that your script helped me start is: Shadows Awakening. It works flawlessly once I applied your fix.

On protondb my report included my own instruction. This is what I prefer to see, a step by step, easy to follow instruction:

1. Go to: https://github.com/z0z0z/mf-install
2. Download and unpack it.
3. Open terminal and `cd` to the location where you unpacked it.
4. Enter two commands (modify the paths, so they would be correct for you):

`export WINEPREFIX="/home/user/SteamLibrary/steamapps/compatdata/585450/pfx/"`

`export PROTON="/home/user/SteamLibrary/steamapps/common/Proton 4.11/"`

Those commands won't create any visible output.

5. Then enter command:

`./mf-install.sh -proton`

If the export paths were correct, you  will see a bunch of output and the success info. If there is a problem, look again at the export paths and correct them. You can try as many times and the success output of the third command will let you know that it worked.

6. Restart Steam.
I didn't do it, so the game run, but froze when starting a new game. After the restart the problem was gone.
