### ISSUE TITLE
Valid pathing

### ISSUE THREAD

**Issue by Lucifer1us** [z0z0z/mf-install#59]
I've been trying to figure this out for a while but it seems like I can't see the mistake in this pathing would you mind taking a look at it.

`luciferius@pop-os:~/mf-install$ WINEPREFIX="~/.steam/debian-installation/steamapps/compatdata/976310/pfx" ./mf-install.sh `

Then it comes with this as the result
`~/.steam/debian-installation/steamapps/compatdata/976310/pfx isn't a valid path`
I'm not too familiar with it so maybe I just can't see whats the mistake

**Comment by z0z0z** [comment]
Wine doesn't like when WINEPREFIX's use `~` as an alias for your home directory.

Replace it with `$HOME` or the actual path of your home directory.

I don't know why Wine in particular won't accept `~`, but it won't.

**Comment by Lucifer1us** [comment]
Thanks that seemed to resolve the pathing error after a couple of attempts
