### ISSUE TITLE
How to install? (Proton)

### ISSUE THREAD

**Issue by gwennshinguji** [z0z0z/mf-install#60]
I'm kind of a noob with custom Wine and Proton prefixes.

I want to play Danganronpa V3 using Proton, however on ProtonDB it tells me I need this script.

I have read over the instructions several times and still really don't understand how I'm meant to use this.

Can anyone give me some instructions?

**Comment by z0z0z** [comment]
Download it, open a terminal in that folder.

Find your Steam game folder, and Proton's Wine prefix for that game inside, it's probably: `$HOME/.local/share/Steam/steamapps/compatdata/567640/pfx`

Run the script with WINEPREFIX environment variable set to that Wine prefix.

`WINEPREFIX="$HOME/.local/share/Steam/steamapps/compatdata/567640/pfx" ./mf-install`

**Comment by gwennshinguji** [comment]
@z0z0z by "Steam game folder" you mean the folder the game is installed in? or the folder Steam is installed in?

**Comment by z0z0z** [comment]
You could have a Steam game/library folder on every drive.

The default one on Linux is $HOME/.local/share/Steam/steamapps

**Comment by gwennshinguji** [comment]
alright, I have my games installed on a different drive. rather than:

`$HOME/.local/share/Steam/steamapps/compatdata`

I would just use the directory the game is installed in, correct?

**Comment by z0z0z** [comment]
Yes.

**Comment by gwennshinguji** [comment]
thanks for your help, dude! :)

**Comment by gwennshinguji** [comment]
upon running:

`WINEPREFIX="$HOME/Games/steamapps/compatdata/567640/pfx" ./mf-install.sh`

I am met with this error:

`cp: cannot stat 'syswow64/*': No such file or directory`
