### ISSUE TITLE
Not working for Greedfall

### ISSUE THREAD

**Issue by nightscope** [z0z0z/mf-install#66]
Hi,
I've installed the latest GE proton and then I followed your instructions and installed the MF in the designated folder. However, the game starts and closes right after in Steam. Any suggestions on how this can be remedied?
Regards

**Comment by z0z0z** [comment]
Don't use both.

Use either Proton-GE only, without this, or this only.

**Comment by nightscope** [comment]
I unchecked to run a specific proton in steam and MF is still installed. However, the same thing keeps happening. I've also tried to run the game only with MF and that also doesn't work. Any other suggestions?
Thank you in advance!

**Comment by nightscope** [comment]
Forget my last comment, I have it working now exactly as you said. I had to reinstall the game and try it out.
