### ISSUE TITLE
installation failed 

### ISSUE THREAD

**Issue by 1111121** [z0z0z/mf-install#69]
everytime i try to install it fails 
how can i solve this problem?

shw@shw-desktop:~/Downloads/mf-install-master$ WINEPREFIX="/home/shw/.steam/steam/steamapps/compatdat/635320/pfx" ./mf-install.sh
'syswow64/colorcnv.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/colorcnv.dll'
'syswow64/mf.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/mf.dll'
'syswow64/mferror.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/mferror.dll'
'syswow64/mfplat.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/mfplat.dll'
'syswow64/mfplay.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/mfplay.dll'
'syswow64/mfreadwrite.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/mfreadwrite.dll'
'syswow64/msmpeg2adec.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/msmpeg2adec.dll'
'syswow64/msmpeg2vdec.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/msmpeg2vdec.dll'
'syswow64/sqmapi.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/syswow64/sqmapi.dll'
'system32/colorcnv.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/colorcnv.dll'
'system32/mf.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/mf.dll'
'system32/mferror.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/mferror.dll'
'system32/mfplat.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/mfplat.dll'
'system32/mfplay.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/mfplay.dll'
'system32/mfreadwrite.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/mfreadwrite.dll'
'system32/msmpeg2adec.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/msmpeg2adec.dll'
'system32/msmpeg2vdec.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/msmpeg2vdec.dll'
'system32/sqmapi.dll' -> '/home/shw/.steam/steam/steamapps/compatdata/635320/pfx/drive_c/windows/system32/sqmapi.dll'
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
The operation completed successfully
neboot.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
gedit.exe: unix/virtual.c:581: free_ranges_remove_range: Assertion `range->base <= view_base && range->end >= view_end' failed.
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Internal error.

**Comment by Aurze** [comment]
I'm getting the same issue, Sadly this was close without explication. Any indication on how to fix this?

**Comment by siepkes** [comment]
@Aurze I also ran in to this issue. You can fix it by specifying the script to use your Steam Proton install instead of you system Wine. For example (adjust for your own Proton folder and game ID):

```
$ PROTON="$HOME/.local/share/Steam/steamapps/common/Proton 5.13/" WINEPREFIX="/mnt/storage1/steam/steamapps/compatdata/839770/pfx" ./mf-install.sh -proton
```
