### ISSUE TITLE
mf-install script broken on wine-staging 6.5

### ISSUE THREAD

**Issue by t14462** [z0z0z/mf-install#78]
OS: Manjaro/Arch

Installer works fine on 6.4

Tested on stock wine and wine-TkG

`The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Invalid address.`

**Comment by t14462** [comment]
Change THIS:
wine start regedit.exe *.reg

To THIS
wine regedit *.reg

**Comment by z0z0z** [comment]
Done ty.
