### ISSUE TITLE
Please make a Release!

### ISSUE THREAD

**Issue by fastrizwaan** [z0z0z/mf-install#89]
Hi kindly make a release, so that we can use it without git in flatpak or on system. thanks

**Comment by z0z0z** [comment]
Done.

**Comment by fastrizwaan** [comment]
Thank you, most unreal engine 4 games need mf-install, as wine implementation is not complete yet.
here's a list
https://en.wikipedia.org/wiki/List_of_Unreal_Engine_games#Unreal_Engine_4
